version: '3'
services:
  server:
    container_name: 'realtime-dash-server'
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    build:
      args:
        PORT: 8000
        PG_URI: "postgres://authdash:authdashpass@db:5432/auth-dash"
        REDIS_URI: "redis://redis:6379"
        JWT_SECRET: ${JWT_SECRET}
        MAILER_USERNAME: ${MAILER_USERNAME}
        MAILER_PASSWORD: ${MAILER_PASSWORD}
        CLIENT_URL: "https://realtime-auth-dashboard.vercel.app"
    ports:
      - 9877:8000

  db:
    image: postgres:14-alpine
    volumes:
      - ./auth-dash-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: authdashpass
      POSTGRES_USER: authdash
      POSTGRES_DB: auth-dash
  redis:
    image: redis:alpine
    ports:
      - "6379"

